plugins {
    id 'com.android.application' version '9.0.1'
    id 'org.jlleitschuh.gradle.ktlint' version '12.1.0'
}

android {
    namespace 'org.fischman.bandwidthmonitor'

    compileSdk 37

    defaultConfig {
        applicationId "org.fischman.bandwidthmonitor"
        minSdk 26
        targetSdk 37
        versionCode 1
        versionName "1.0"
    }

    buildTypes {
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard.pro'
            signingConfig signingConfigs.debug
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_21
        targetCompatibility JavaVersion.VERSION_21
    }
}

kotlin {
    compilerOptions {
        jvmTarget = org.jetbrains.kotlin.gradle.dsl.JvmTarget.JVM_21
    }
}

dependencies {}
